### ISSUE TITLE
Error installing hooks (guppy-pre-commit)

### ISSUE THREAD

**Issue by vasily-shakhov** [therealklanni/git-guppy#34]
Windows 8x64,  git version 2.5.0.windows.1, npm 2.11.3, nodejs v0.12.7

Steps:
1. Create new folder
2. run "git init"
3. run "npm init"
4. run "npm install git-guppy"
5. run npm install guppy-pre-commit

Error message:
npm WARN package.json test12@1.0.0 No description
npm WARN package.json test12@1.0.0 No repository field.
npm WARN package.json test12@1.0.0 No README data
\
> spawn-sync@1.0.13 postinstall c:\Cengage\test12\node_modules\guppy-pre-commit\
node_modules\guppy-cli\node_modules\yargs\node_modules\os-locale\node_modules\ex
ec-file-sync\node_modules\spawn-sync
> node postinstall

> guppy-pre-commit@0.2.1 postinstall c:\Cengage\test12\node_modules\guppy-pre-co
mmit
> guppy pre-commit

net.js:633
    throw new TypeError('invalid data');
          ^
TypeError: invalid data
    at WriteStream.Socket.write (net.js:633:11)
    at execFileSync (child_process.js:1364:20)
    at Function.module.exports.sync (c:\Cengage\test12\node_modules\guppy-pre-co
mmit\node_modules\guppy-cli\node_modules\yargs\node_modules\os-locale\index.js:7
8:16)
    at Argv (c:\Cengage\test12\node_modules\guppy-pre-commit\node_modules\guppy-
cli\node_modules\yargs\index.js:22:22)
    at Object.<anonymous> (c:\Cengage\test12\node_modules\guppy-pre-commit\node_
modules\guppy-cli\node_modules\yargs\index.js:10:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "guppy-pre-commit"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! guppy-pre-commit@0.2.1 postinstall: `guppy pre-commit`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the guppy-pre-commit@0.2.1 postinstall script 'guppy pre-comm
it'.
npm ERR! This is most likely a problem with the guppy-pre-commit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     guppy pre-commit
npm ERR! You can get their info via:
npm ERR!     npm owner ls guppy-pre-commit
npm ERR! There is likely additional logging output above.

Can you provide any help, please?

**Comment by vasily-shakhov** [comment]
I've fixed the problem.
The problem was in package os-locale, line 
var stdout = execFileSync('wmic', ['os', 'get', 'locale'], {encoding: 'utf8'});

wmic.exe was not in classpath.
I've added wmic.exe in windows classpath and all working ok. Close this please
