### ISSUE TITLE
Error: Adding a 

### ISSUE THREAD

**Issue by bassettsj** [therealklanni/git-guppy#40]
Hey thanks for a great project. It has been working really well for the most part but, occasionally I am getting a strange error when the file can't be read.

I am running running on Node v5.0.0 on OSX 10.10

```
shell.js: internal error
Error: ENOENT: no such file or directory, open '/var/folders/x7/vd9x30kn449c40tfrx329cm40000gq/T/shelljs_fb6c1ea57c0eb32e296e'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at execSync (~/app/node_modules/git-guppy/node_modules/shelljs/src/exec.js:105:24)
    at _exec (~/app/node_modules/git-guppy/node_modules/shelljs/src/exec.js:210:12)
    at ~/app/node_modules/git-guppy/node_modules/shelljs/src/common.js:182:23
    at ~/app/node_modules/git-guppy/lib/get-hook.js:27:22
    at wrappedMapper (~/app/node_modules/map-stream/index.js:84:19)
    at Stream.stream.write (~/app/node_modules/map-stream/index.js:96:21)
    at write (~/app/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
```

Let me know if there is anything I can do to help solve or diagnose the issue.

**Comment by bassettsj** [comment]
CC: @elimak & @nastiatikk

**Comment by therealklanni** [comment]
Interesting. I'll upgrade to npm 5 and do some testing. Thanks for the report.

**Comment by therealklanni** [comment]
I just published git-guppy v1.0.1 which fixed a similar issue. Please try updating git-guppy and let me know if you're still having this issue.

**Comment by bassettsj** [comment]
Okay. Let me try that.

**Comment by nastiatikk** [comment]
I've updated git-guppy to v1.0.1 but still sometimes see this error. And it's not consistent, sometimes it happens every second time, sometimes every 5th, sometimes after first pre-commit message, sometimes after last one, sometimes after one in the middle (shrug)…

```
shell.js: internal error
Error: ENOENT: no such file or directory, open '/var/folders/qn/3lmq_g9s21bf7fl_p8fr5d4m0000gn/T/shelljs_e4d8d1f573fea284fa28'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at execSync (~/node_modules/git-guppy/node_modules/shelljs/src/exec.js:105:24)
    at _exec (~/node_modules/git-guppy/node_modules/shelljs/src/exec.js:210:12)
    at ~/node_modules/git-guppy/node_modules/shelljs/src/common.js:182:23
    at ~/node_modules/git-guppy/lib/get-hook.js:27:22
    at wrappedMapper (~/node_modules/map-stream/index.js:84:19)
    at Stream.stream.write (~/node_modules/map-stream/index.js:96:21)
    at write (~/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (~/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (~/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at emitReadable_ (~/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (~/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:444:5)
```

It also always tells `Requiring external module babel-core/register` even though babel-core was installed (don't know if it's necessary information).
